### PR TITLE
some enhancements for the site extension

### PR DESCRIPTION
**Pull request by larseidam**
with the dispedia development i have made some enhancements for this extension, here is a little overview
- first I added language support for _literal_ and _img_ helper. It's useful if you have different language on the website and the extension should use the statement in the selected language
- the second feature is, that the _sites_ folder are now really changeable. Before you was able to change the folder in the doap file, but the references to this folder are still alive, because the are hard coded in the controller, now you are able to really change the folder to any place you want (also outside the extension)
- the third one is a table helper, so you can add specific statements to the site model and the helper generate a table from this statements (also with language support, like the first feature). To use this you have a main property, like this
  `http://ns.ontowiki.net/SysOnt/Site/tableContent`, then the cells were filled with the content of the following properties

```
http://ns.ontowiki.net/SysOnt/Site/tableContentR1C1
http://ns.ontowiki.net/SysOnt/Site/tableContentR2C1
http://ns.ontowiki.net/SysOnt/Site/tableContentR1C2
```

and the size will be set by

```
http://ns.ontowiki.net/SysOnt/Site/tableContentRows
http://ns.ontowiki.net/SysOnt/Site/tableContentColumns
```

With this you can generate a table and can change the content and the size dynamically. I don't know if this is a correct or good semantic representation of a table, but anyway i needed a table one the website.
If you want to look at a example, look at www.dispedia.de.

Maybe you want to include some of this features, feel free to do it. :)

### CODE REVIEW

**Comment by seebi** [comment]
@larseidam This sounds really awesome for me, thank you very much.

**Comment by seebi** [comment]
@white-gecko regarding https://github.com/AKSW/aksw.org/issues/48 - can you merge this pull request too?

**Comment by white-gecko** [comment]
Regarding the language support: Does the language support read the `Accept-Language` header [1]?

Regarding the table feature and your question “I don't know if this is a correct or good semantic representation of a table …”: I think it would be cool if you can define a query which selects the resources to display (per row) and a list (or array) of query-variables (strings) to define which of the query-variables should be displayed and in which order (as columns). Would this also fit your desired use-case?

[1] https://en.wikipedia.org/wiki/Accept-Language#Accept-Language

**Comment by seebi** [comment]
regarding language: it uses OntoWiki::getInstance()->getConfig()->languages->locale which is set in bootstrap.

Since a search for `Accept-Language` does not reveal any hits, I think the anser is "no" ....

**Comment by seebi** [comment]
but using `OntoWiki::getInstance()->getConfig()->languages->locale` in the context of this extension I think.

**Comment by seebi** [comment]
So I give my merge-ok. Nate can you do that (and test it with aksw.org)

**Pull request merged**
